keys:
  - &keanu age18lx82lrvujvlhn43hwkf8j0rpp4qr2f960zslw540t7er2kfqdxqfyjz3h
  - &beehive age14lxqlxv6jr4xdjycfcvsge6rw4p0md92qcp6k9ht74szqwur239qd6r7nt
  - &earth age1x9u24y30w4xkv3x3tvq2dpjpd0azamldxle06q5md93gtkt93qfqfl847z
  - &hyperion age1wkz9wascfp6zwja7clc4lmhz8dnh9d34vv9rwdmgth7xcq9rdaes6mdmx2
  - &luna age1zffxzktzsm0h45dqy5mttkcvgwr5l2fwj4a324mt633y074l7pfqnca0er
  - &mars age1l7hnwe4qv8dhswrwf0euzk3wzec6w79guaydj0tc7wu00d8xxs9q6j8jf2
  - &phoebe age1jn7t5d6hv3amkpjzx7skypg5jtj63elkrvenhp89ngjv43rdkvesc0sxfc
  - &salacia age13xkeqkwq4a97p06wvyvt354rzf897qatzf8vzr8zzn6hcujlucdqn7dsdm
  - &titan age12n97ecag67n5gyjsjqv3kgplpsjcgej6tf6aehp87sfst7n3yqsq99mar8
  - &ursa age1e4d8esn4e3ud8xskufs6ttmj6mv7mdg6kdmcm9mmfz6esq55nq5qdp6pz5
creation_rules:
  - path_regex: secrets/sops/secrets.yaml$
    key_groups:
      - age:
          - *keanu
          - *beehive
          - *earth
          - *hyperion
          - *luna
          - *mars
          - *phoebe
          - *salacia
          - *titan
          - *ursa
