[buffer.channel.topic]
enabled = true

[font]
family = "Iosevka Term"
size = 18

[servers.liberachat]
channels = [
    "#archlinux",
    "#gnome",
    "#halloy",
    "#halloy-dev",
    "#libera",
    "#linux",
    "#nixos",
    "#nixos-chat",
    "#nixos-dev",
    "#nix-darwin",
    "#plug",
]
nickname = "keanu2"
port = 6697
server = "irc.libera.chat"

[servers.hackint]
channels = ["#nixos"]
nickname = "keanu2"
port = 6697
server = "irc.hackint.org"

[servers.oftc]
channels = ["#bcache"]
nickname = "keanu2"
port = 6697
server = "irc.oftc.net"

[theme]
dark = "ferra"
light = "ferra-light"
