# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c08a8a62-b449-424f-8c18-e749289120c3";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/a0b9696f-8a05-4344-ae94-8758738b35a1";

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/c08a8a62-b449-424f-8c18-e749289120c3";
    fsType = "btrfs";
    options = ["subvol=@nix"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/c08a8a62-b449-424f-8c18-e749289120c3";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/c08a8a62-b449-424f-8c18-e749289120c3";
    fsType = "btrfs";
    options = ["subvol=@snapshots"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/c08a8a62-b449-424f-8c18-e749289120c3";
    fsType = "btrfs";
    options = ["subvol=@var_log"];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/c08a8a62-b449-424f-8c18-e749289120c3";
    fsType = "btrfs";
    options = ["subvol=@swap"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8B7B-A82C";
    fsType = "vfat";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
