{ ... }:

{
  homebrew = {
    enable = true;
    taps = [
      "homebrew/cask"
      "homebrew/core"
    ];
    brews = [];
    casks = [
      "alacritty"
      "audacity"
      "battle-net"
      "beeper"
      "bruno"
      "calibre"
      "chromium"
      "cmake"
      "darktable"
      "dbeaver-community"
      "discord"
      "docker"
      "element"
      "epic-games"
      "firefox"
      "firefox@developer-edition"
      "gimp"
      "github@beta"
      "google-drive"
      "handbrake"
      "insomnia"
      "iterm2@beta"
      "jetbrains-toolbox"
      "kdenlive"
      "kitty"
      "libreoffice"
      "messenger"
      "microsoft-teams"
      "nvidia-geforce-now"
      "obs"
      "podman-desktop"
      "postman"
      "proton-drive"
      "proton-mail"
      "proton-pass"
      "protonmail-bridge"
      "protonvpn"
      "signal"
      "skype@preview"
      "standard-notes"
      "steam"
      "telegram"
      "thunderbird"
      "thunderbird@beta"
      "transmission"
      "virtualbox"
      "visual-studio-code"
      "visual-studio-code@insiders"
      "vlc"
      "vscodium"
      "whatsapp"
      "wireshark"
      "zed"
      "zed@preview"
      "zoom"
    ];
  };
}
