{
  pkgs,
  inputs,
  ...
}: {
  home.packages = with pkgs; [
    alpaca
    android-studio
    android-tools
    appimage-run
    audacity
    bitwarden-desktop
    bottles
    calibre
    caprine
    catppuccin
    darktable
    dbeaver-bin
    discord
    element-desktop
    endeavour
    ente-auth
    ente-cli
    ente-desktop
    foliate
    fractal
    fragments
    gimp3-with-plugins
    github-desktop
    gnome-builder
    gnome-disk-utility
    gnome-maps
    handbrake
    inkscape
    insomnia
    jellyfin-media-player
    jitsi
    joplin-desktop
    krita
    kodi-wayland
    leetcode-cli
    leetgo
    libreoffice
    librewolf
    lmstudio
    logseq
    lollypop
    netbird-dashboard
    netbird-ui
    nextcloud-client
    obs-studio
    pitivi
    plex-desktop
    plexamp
    pocket-casts
    podman-desktop
    polari
    proton-pass
    protonmail-desktop
    protonmail-bridge-gui
    protonvpn-gui
    rawtherapee
    rustdesk-flutter
    session-desktop
    shortwave
    shotwell
    signal-desktop-bin
    slack
    standardnotes
    steam-run
    stellarium
    telegram-desktop
    transmission_4-gtk
    trayscale
    tremotesf
    tuba
    typst
    vlc
    wireshark
    wl-clipboard
    xclip
    youtube-music
    zlib-ng

    androidStudioPackages.beta
    androidStudioPackages.dev

    kdePackages.kdenlive
    kdePackages.kdevelop

    inputs.zen-browser.packages."${system}".default

    # Games
    airshipper
    bugdom
    flightgear
    heroic
    lutris
    nanosaur
    nanosaur2
    otto-matic
    shattered-pixel-dungeon
    superTux
    superTuxKart
    wesnoth
    xonotic
    zeroad
  ];
}
