# Issue: nixarr sets `LoadCredential = mkForce null` on the autobrr unit while nixpkgs'
#   services.autobrr leaves `Environment = AUTOBRR__SESSION_SECRET_FILE=%d/sessionSecret`
#   in place, so autobrr looks for a systemd credential that is never provided.
# Description: Clear the inherited Environment so autobrr falls back to the session
#   secret in its config file (generated by nixarr's own ExecStartPre).
#   The dasel-v3 half of this workaround was fixed upstream in nixarr PR #172 (2026-06-09).
# Status: active
# Last-checked: 2026-08-22
# Removal condition: Remove when nixarr either unsets AUTOBRR__SESSION_SECRET_FILE
#   or provides the credential.
{ config, ... }:
{
  flake.modules.nixos.nixarr-autobrr-dasel-v3 =
    {
      config,
      lib,
      options,
      ...
    }:
    lib.mkIf ((options ? nixarr) && config.nixarr.autobrr.enable) {
      systemd.services.autobrr.serviceConfig.Environment = lib.mkForce [ ];
    };

  flake.modules.nixos.nixarr = config.flake.modules.nixos.nixarr-autobrr-dasel-v3;
}
