name: Check Links

on:
  schedule:
    - cron: "0 0 * * 1"  # Weekly
  workflow_dispatch:

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress '**/*.md' '**/*.nix'
